# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://higgsbosonhealth.com
title: Higgs Boson Health Inc.
email: hello@higgsbosonhealth.com
author: Rajeev Dharmapurikar
description: > # "Write an awesome description for your new site here.
  You can edit this line in _config.yml. It will appear in your document
  head meta (for Google search results) and in your feed.xml site
  description.
copyright: 'Copyright &copy; 2016 Higgs Boson Helath Inc. All Rights Reserved.'
credits: ''

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  # - title: twitter
  #   url: https://twitter.com/SBootstrap
  # - title: github
  #   url: https://github.com/IronSummitMedia/startbootstrap
  # - title: linkedin
  #   url:
